### ISSUE TITLE
Feature Request: DateTime component

### ISSUE THREAD

**Issue by CogitoGroupDevTeam** [LLKennedy/imagetemplate#1]
DateTime values can be rendered as pre-configured Text components, but dedicated DateTime components with the ability to pass time.Time or formatted time strings as arguments with template-configurable time formatting would be useful.

Example component structures:
`{
    "type": "dateTime",
    "properties": {
        "content": "$myDateVar$",
        "inFormat": "time.Time",
        "outFormat": "02 Jan 2006",
        "startX": "10",
        "startY": "10",
        "maxWidth": "100",
        "size": "15",
        "font": {
            "fontName": "goregular"
        },
        "colour": {
            "R": "0",
            "G": "0",
            "B": "0",
            "A": "255"
        }
    }
},
{
    "type": "dateTime",
    "properties": {
        "content": "$myDateVar$",
        "inFormat": "time.Time",
        "format": "02/01/06",
        "startX": "10",
        "startY": "10",
        "maxWidth": "100",
        "size": "15",
        "font": {
            "fontName": "goregular"
        },
        "colour": {
            "R": "0",
            "G": "0",
            "B": "0",
            "A": "255"
        }
    }
},
{
    "type": "dateTime",
    "properties": {
        "content": "09||6|24",
        "inFormat": "01||2||06",
        "outFormat": "Mon Jan 2 '06",
        "startX": "10",
        "startY": "10",
        "maxWidth": "100",
        "size": "15",
        "font": {
            "fontName": "goregular"
        },
        "colour": {
            "R": "0",
            "G": "0",
            "B": "0",
            "A": "255"
        }
    }
}`

**Comment by LLKennedy** [comment]
Functional DateTime component has been included in release v2.0.0
